let analysisBusy=false,programData=null,scaffoldData=null,analysisInputs='';
function invalidatePrograms(){const signature=[...docs.values()].map(d=>d.publication+':'+d.source_snapshot?.sha256).sort().join('|');if(signature!==analysisInputs){analysisInputs=signature;programData=null;scaffoldData=null;clear('program-result');clear('scaffold-result');$('program-status').textContent='专利集合已更新，请重新分析。'}}
async function analysisCall(path,publications){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({publications})});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
function analysisDownload(label,data,name){return action(label,()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)})}
$('analyse-programs').onclick=async()=>{if(analysisBusy||busy)return;analysisBusy=true;const inputSignature=analysisInputs;$('analyse-programs').disabled=true;$('program-status').textContent='正在提取信号并计算候选分组…';clear('scaffold-result');try{const d=await analysisCall('/api/programs',[...docs.keys()]);if(analysisInputs!==inputSignature)return;programData=d;drawPrograms(d);$('program-status').textContent='已完成候选分组；尚待人工确认。'}catch(e){$('program-status').textContent=e.message}finally{analysisBusy=false;$('analyse-programs').disabled=false}};
function drawPrograms(d){
 const box=clear('program-result');box.append(el('p',d.notice,'note'),el('p','阈值 '+d.config.threshold+'；权重：发明人 '+d.config.weights.inventors+' / 骨架 '+d.config.weights.scaffolds+' / 靶点 '+d.config.weights.targets),analysisDownload('下载程序分析 JSON',d,'program-analysis.json'));
 const families=new Map(d.families.map(f=>[f.id,f]));
 d.programs.forEach(p=>{const card=el('article',undefined,'panel');card.append(el('h3',p.status==='candidate_program'?'候选程序 · '+p.id:'未归组家族'),el('p','以下按来源优先权日排序，不标记历史代际。'));
 p.families.forEach(id=>{const f=families.get(id);card.append(el('p',(f.priority_date||'日期未知')+' · '+f.publications.join(' / ')+' · '+f.evidence_molecules+' 个独立证据结构'),el('p','申请人：'+f.assignees_raw.join(' / ')+' → '+f.assignees.join(' / ')),el('p','发明人数 '+f.inventors.length+'；靶点提及 '+(f.targets.join(' / ')||'未识别')));const details=el('details');details.append(el('summary','查看元数据、靶点原文及来源'),el('p','发明人：'+f.inventors.join(' / ')));f.target_evidence.forEach(t=>details.append(el('p',t.target+' · '+t.field+'：'+t.excerpt),link('核查原文',t.url)));f.sources.forEach(s=>details.append(link(s.publication,s.url),el('p',s.snapshot?.sha256||'快照缺失','break')));card.append(details)});
 card.append(action('对齐此组证据结构与 R 基团',()=>runScaffolds(p.publications)));box.append(card)});
 box.append(el('h3','成对信号与未合并原因'));
 d.pairs.forEach(p=>{const details=el('details');details.append(el('summary',p.a+' ↔ '+p.b+' · '+p.score+(p.eligible?' · 满足候选条件':' · 未合并')));for(const key of ['inventors','scaffolds','targets'])details.append(el('p',({inventors:'发明人重叠',scaffolds:'骨架信号',targets:'靶点提及重叠'})[key]+'：'+(p.signals[key]===null?'缺失':p.signals[key].toFixed(3))));details.append(el('p','骨架方法：'+p.scaffold_detail.method+'；网络 Jaccard '+p.scaffold_detail.network_jaccard+'；有信息环系 Jaccard '+p.scaffold_detail.ring_jaccard),el('p','共有非通用环系：'+p.scaffold_detail.shared_informative_rings.join(' / ')),el('p','共有发明人：'+p.shared.inventors.join(' / ')),el('p',p.reasons.join('；')||'满足成对候选条件；合并还要求组内全部跨家族配对通过，避免链式误合并。'));box.append(details)});
 box.append(el('h3','手动选择结构对齐范围'),el('p','可跨候选组比较；这不会把所选家族标为同一研发程序。'));
 const controls=el('div',undefined,'row');d.families.forEach(f=>{const label=el('label');const input=el('input');input.type='checkbox';input.style.minWidth='auto';input.dataset.analysisFamily=f.id;input.checked=true;label.append(input,document.createTextNode(f.publications.join(' / ')));controls.append(label)});box.append(controls,action('对齐勾选家族的证据结构',()=>{const selected=[...controls.querySelectorAll('input:checked')].flatMap(n=>families.get(n.dataset.analysisFamily).publications);if(!selected.length){$('program-status').textContent='请至少选择一个家族。';return}runScaffolds(selected)}));
}
async function runScaffolds(publications){if(analysisBusy||busy)return;analysisBusy=true;const signature=analysisInputs;const box=clear('scaffold-result');box.append(el('p','正在建立骨架网络并分解 R 基团…'));try{const d=await analysisCall('/api/scaffolds',publications);if(analysisInputs!==signature)return;scaffoldData=d;drawScaffolds(d)}catch(e){box.replaceChildren(el('p',e.message,'error'))}finally{analysisBusy=false}}
function drawScaffolds(d){
 const box=clear('scaffold-result');box.append(el('h2','骨架与 R 基团对齐'),el('p',d.notice,'note'),el('p',d.input_cards+' 张证据卡 / '+d.unique_molecules+' 个不同结构；状态 '+d.status),el('p',d.reason||''),analysisDownload('下载骨架与 R 基团 JSON',d,'scaffold-analysis.json'));
 if(d.excluded.length)box.append(el('p','排除：'+d.excluded.map(x=>x.publication+' '+x.label+' '+x.reason).join('；')));
 if(d.network){const details=el('details');details.append(el('summary','骨架网络：'+d.network.nodes.length+' 个节点 / '+d.network.edges.length+' 条边'));d.network.nodes.forEach(n=>details.append(el('p',n.atoms+' 原子 · 覆盖 '+n.support.length+'/'+d.unique_molecules+' · '+n.smiles)));box.append(details)}
 if(!d.anchor)return;
 box.append(el('h3','本次共同锚点'),el('p',d.anchor.method+' · '+d.anchor.atoms+' 重原子；分子覆盖率 '+Math.round(100*d.anchor.coverage_min)+'%–'+Math.round(100*d.anchor.coverage_max)+'%'));
 if(d.anchor.low_coverage)box.append(el('p','覆盖不足 60%：仅比较局部共同结构，不自动判定骨架跃迁。','note'));
 if(d.anchor.alternative_matches.some(n=>n>1))box.append(el('p','存在多个子结构匹配（计数最多 16）；R 位点分配具有对称歧义，需结合原图复核。','note'));
 if(d.anchor.svg){const card=el('div',undefined,'card');const img=el('img');img.src=d.anchor.svg;img.alt='带本次 R 标签的共同核心';card.append(img);box.append(card)}
 box.append(el('pre',d.anchor.smarts));
 const grid=el('div',undefined,'grid');d.rows.forEach(r=>{const card=el('article',undefined,'card');card.append(el('h3',r.publication+' / '+r.label));const img=el('img');img.src=r.svg;img.alt=r.label+' 对齐输入结构';card.append(img,link('结构原图',r.source.url));if(!r.matched)card.append(el('p','未匹配，不填充 R 位点。'));else{const table=el('table');d.labels.forEach(label=>{const tr=el('tr');const cell=el('td');if(r.fragment_svgs?.[label]){const img=el('img');img.src=r.fragment_svgs[label];img.alt=label+' 片段';img.style.height='100px';cell.append(img)}cell.append(el('small',r.fragments[label]??'未分配'));tr.append(el('th',label),cell);table.append(tr)});card.append(table);if(r.bridged_labels.length)card.append(el('p',r.bridged_labels.join(' / ')+' 为多连接点片段，同一桥连片段可能出现在多个 R 列，不能独立计作多次替换。','note'))}grid.append(card)});box.append(grid);
 box.append(el('h3','按日期并列的片段差异（非历史步骤）'));(d.family_comparisons||[]).forEach(c=>{const card=el('div',undefined,'panel');card.append(el('strong',c.a+' ↔ '+c.b),el('p',c.notice));c.differences.forEach(v=>card.append(el('p',v.label+' · 两侧匹配分子数 '+v.a_matched+' / '+v.b_matched),el('pre','仅 A 样本出现：'+(v.only_in_a.join('；')||'无')+'\n仅 B 样本出现：'+(v.only_in_b.join('；')||'无'))));if(!c.differences.length)card.append(el('p','当前已匹配样本没有 R 片段集合差异。'));box.append(card)});
 const freq=el('details');freq.append(el('summary','按家族统计 R 片段支持数（独立分子去重）'));d.site_frequencies.forEach(f=>freq.append(el('p','家族 '+f.family+' / '+f.label+'：匹配 '+f.matched_unique+'/'+f.total_unique+'；未分配 '+f.missing),el('pre',f.variants.map(v=>v.count+' 个：'+v.smiles).join('\n'))));box.append(freq);
}
